


// Aura Reading Advisors
export const auraReadingAdvisors = [
  {
    id: "aura1",
    name: "Sophia Luna",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Energy Healing", "Chakra Balancing"],
    description:
      "Sophia can see and interpret the colors of your aura, revealing your emotional, mental, and spiritual state. Her readings provide deep insights into your energy field.",
    rating: 5,
    reviewCount: 432,
    status: "online",
    latestReview: {
      name: "Mira",
      text: "Sophia's aura reading was incredibly accurate. She identified energy blockages I've been struggling with for years.",
      rating: 5,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "aura2",
    name: "Rajan Mehta",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Photography", "Spiritual Cleansing", "Meditation"],
    description:
      "With over 15 years of experience, Rajan specializes in detailed aura analysis and provides personalized cleansing techniques.",
    rating: 4,
    reviewCount: 289,
    status: "busy",
    latestReview: {
      name: "Thomas",
      text: "The aura cleansing techniques Rajan taught me have transformed my daily life. I feel lighter and more balanced.",
      rating: 5,
    },
    callRate: 1.95,
    chatRate: 1.65,
  },
  {
    id: "aura3",
    name: "Elena Vasquez",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Past Life Connection", "Intuitive Healing"],
    description:
      "Elena can detect past life influences in your aura and help you understand how they affect your current life path and relationships.",
    rating: 5,
    reviewCount: 356,
    status: "offline",
    latestReview: {
      name: "Sarah",
      text: "Elena connected dots between my past lives and current challenges that completely changed my perspective.",
      rating: 5,
    },
    callRate: 2.25,
    chatRate: 1.95,
  },
  {
    id: "aura4",
    name: "Kai Nakamura",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Photography", "Energy Field Analysis", "Kirlian Photography"],
    description:
      "Using specialized techniques, Kai captures and interprets your aura's visual representation, providing insights into your energetic state.",
    rating: 4,
    reviewCount: 178,
    status: "online",
    latestReview: {
      name: "Jessica",
      text: "The aura photograph analysis was fascinating and surprisingly accurate about my current life situation.",
      rating: 4,
    },
    callRate: 1.85,
    chatRate: 1.55,
  },
  {
    id: "aura5",
    name: "Amara Johnson",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Crystal Therapy", "Sound Healing"],
    description:
      "Amara combines aura reading with crystal and sound therapy to not only identify but also heal imbalances in your energy field.",
    rating: 5,
    reviewCount: 412,
    status: "busy",
    latestReview: {
      name: "Michael",
      text: "The combination of aura reading and sound healing was powerful. I felt the energy shifts happening during our session.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "aura1",
    name: "Sophia Luna",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Energy Healing", "Chakra Balancing"],
    description:
      "Sophia can see and interpret the colors of your aura, revealing your emotional, mental, and spiritual state. Her readings provide deep insights into your energy field.",
    rating: 5,
    reviewCount: 432,
    status: "online",
    latestReview: {
      name: "Mira",
      text: "Sophia's aura reading was incredibly accurate. She identified energy blockages I've been struggling with for years.",
      rating: 5,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "aura2",
    name: "Rajan Mehta",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Photography", "Spiritual Cleansing", "Meditation"],
    description:
      "With over 15 years of experience, Rajan specializes in detailed aura analysis and provides personalized cleansing techniques.",
    rating: 4,
    reviewCount: 289,
    status: "busy",
    latestReview: {
      name: "Thomas",
      text: "The aura cleansing techniques Rajan taught me have transformed my daily life. I feel lighter and more balanced.",
      rating: 5,
    },
    callRate: 1.95,
    chatRate: 1.65,
  },
  {
    id: "aura3",
    name: "Elena Vasquez",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Past Life Connection", "Intuitive Healing"],
    description:
      "Elena can detect past life influences in your aura and help you understand how they affect your current life path and relationships.",
    rating: 5,
    reviewCount: 356,
    status: "offline",
    latestReview: {
      name: "Sarah",
      text: "Elena connected dots between my past lives and current challenges that completely changed my perspective.",
      rating: 5,
    },
    callRate: 2.25,
    chatRate: 1.95,
  },
  {
    id: "aura4",
    name: "Kai Nakamura",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Photography", "Energy Field Analysis", "Kirlian Photography"],
    description:
      "Using specialized techniques, Kai captures and interprets your aura's visual representation, providing insights into your energetic state.",
    rating: 4,
    reviewCount: 178,
    status: "online",
    latestReview: {
      name: "Jessica",
      text: "The aura photograph analysis was fascinating and surprisingly accurate about my current life situation.",
      rating: 4,
    },
    callRate: 1.85,
    chatRate: 1.55,
  },
  {
    id: "aura5",
    name: "Amara Johnson",
    image: "/images/advisorss_1.jpg",
    skills: ["Aura Reading", "Crystal Therapy", "Sound Healing"],
    description:
      "Amara combines aura reading with crystal and sound therapy to not only identify but also heal imbalances in your energy field.",
    rating: 5,
    reviewCount: 412,
    status: "busy",
    latestReview: {
      name: "Michael",
      text: "The combination of aura reading and sound healing was powerful. I felt the energy shifts happening during our session.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
]

// Crystal Reading Advisors
export const crystalReadingAdvisors = [
  {
    id: "crystal1",
    name: "Jasper Stone",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Reading", "Lithomancy", "Energy Alignment"],
    description:
      "Jasper uses ancient crystal reading techniques to reveal hidden truths and provide guidance on your life's most pressing questions.",
    rating: 5,
    reviewCount: 521,
    status: "online",
    latestReview: {
      name: "Olivia",
      text: "Jasper's crystal reading was incredibly detailed. He connected with energies I didn't even know were affecting me.",
      rating: 5,
    },
    callRate: 2.25,
    chatRate: 1.95,
  },
  {
    id: "crystal2",
    name: "Luna Quartz",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Energy", "Chakra Balancing", "Gemstone Therapy"],
    description:
      "Luna specializes in identifying which crystals resonate with your energy and can help you overcome specific challenges in your life.",
    rating: 4,
    reviewCount: 347,
    status: "busy",
    latestReview: {
      name: "Daniel",
      text: "The crystals Luna recommended have made a noticeable difference in my anxiety levels. Her insights were spot on.",
      rating: 4,
    },
    callRate: 1.85,
    chatRate: 1.55,
  },
  {
    id: "crystal3",
    name: "Amber Rose",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Grid Reading", "Manifestation", "Spiritual Guidance"],
    description:
      "Amber creates personalized crystal grids that amplify your intentions and help manifest your desires with greater clarity and power.",
    rating: 5,
    reviewCount: 289,
    status: "offline",
    latestReview: {
      name: "Jordan",
      text: "After following Amber's crystal grid instructions, I received the job offer I'd been hoping for within a week!",
      rating: 5,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "crystal4",
    name: "Jade Wong",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Reading", "Ancient Wisdom", "Healing Arts"],
    description:
      "Combining Eastern and Western crystal traditions, Jade offers unique insights that bridge ancient wisdom with modern challenges.",
    rating: 5,
    reviewCount: 412,
    status: "online",
    latestReview: {
      name: "Samantha",
      text: "Jade's crystal reading was transformative. She helped me understand patterns I've been stuck in for years.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "crystal1",
    name: "Jasper Stone",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Reading", "Lithomancy", "Energy Alignment"],
    description:
      "Jasper uses ancient crystal reading techniques to reveal hidden truths and provide guidance on your life's most pressing questions.",
    rating: 5,
    reviewCount: 521,
    status: "online",
    latestReview: {
      name: "Olivia",
      text: "Jasper's crystal reading was incredibly detailed. He connected with energies I didn't even know were affecting me.",
      rating: 5,
    },
    callRate: 2.25,
    chatRate: 1.95,
  },
  {
    id: "crystal2",
    name: "Luna Quartz",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Energy", "Chakra Balancing", "Gemstone Therapy"],
    description:
      "Luna specializes in identifying which crystals resonate with your energy and can help you overcome specific challenges in your life.",
    rating: 4,
    reviewCount: 347,
    status: "busy",
    latestReview: {
      name: "Daniel",
      text: "The crystals Luna recommended have made a noticeable difference in my anxiety levels. Her insights were spot on.",
      rating: 4,
    },
    callRate: 1.85,
    chatRate: 1.55,
  },
  {
    id: "crystal3",
    name: "Amber Rose",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Grid Reading", "Manifestation", "Spiritual Guidance"],
    description:
      "Amber creates personalized crystal grids that amplify your intentions and help manifest your desires with greater clarity and power.",
    rating: 5,
    reviewCount: 289,
    status: "offline",
    latestReview: {
      name: "Jordan",
      text: "After following Amber's crystal grid instructions, I received the job offer I'd been hoping for within a week!",
      rating: 5,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "crystal4",
    name: "Jade Wong",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Crystal Reading", "Ancient Wisdom", "Healing Arts"],
    description:
      "Combining Eastern and Western crystal traditions, Jade offers unique insights that bridge ancient wisdom with modern challenges.",
    rating: 5,
    reviewCount: 412,
    status: "online",
    latestReview: {
      name: "Samantha",
      text: "Jade's crystal reading was transformative. She helped me understand patterns I've been stuck in for years.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
]

// Pet Psychics Advisors
export const petPsychicsAdvisors = [
  {
    id: "pet1",
    name: "Whisper Wilson",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Animal Communication", "Pet Behavior", "Lost Pet Location"],
    description:
      "Whisper can communicate with your pets to understand their needs, behaviors, and help resolve issues they can't express to you directly.",
    rating: 5,
    reviewCount: 478,
    status: "online",
    latestReview: {
      name: "Emma",
      text: "Whisper told me exactly why my cat was avoiding the litter box - it was a health issue the vet later confirmed!",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "pet2",
    name: "Bark Thompson",
    image: "/images/advisorss_2.jpg",
    skills: ["Pet Medium", "Animal Afterlife", "Grief Counseling"],
    description:
      "Bark specializes in connecting with pets who have crossed over, bringing closure and healing messages from your beloved companions.",
    rating: 5,
    reviewCount: 532,
    status: "busy",
    latestReview: {
      name: "Robert",
      text: "The details Bark knew about my deceased dog were impossible to guess. The message he delivered brought me to tears and gave me peace.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "pet3",
    name: "Feather Martinez",
    image: "/images/advisorss_2.jpg",
    skills: ["Bird Whisperer", "Wildlife Communication", "Exotic Pets"],
    description:
      "Feather has a special connection with birds and exotic animals, helping owners understand the unique needs of their unusual companions.",
    rating: 4,
    reviewCount: 187,
    status: "offline",
    latestReview: {
      name: "Tyler",
      text: "My parrot's behavior completely changed after implementing Feather's suggestions. She truly understands avian psychology.",
      rating: 4,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "pet4",
    name: "Paws Peterson",
    image: "/images/advisorss_2.jpg",
    skills: ["Pet Trauma Healing", "Behavioral Issues", "Animal Empathy"],
    description:
      "Paws works with rescue animals and pets with trauma, helping them heal emotional wounds and adapt to new environments.",
    rating: 5,
    reviewCount: 321,
    status: "online",
    latestReview: {
      name: "Melissa",
      text: "My rescue dog was terrified of men until Paws helped me understand his past trauma. His transformation has been remarkable.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "pet5",
    name: "Fin Aquarius",
    image: "/images/advisorss_2.jpg",
    skills: ["Aquatic Animals", "Pet Health Intuitive", "Energy Healing for Animals"],
    description:
      "Fin specializes in aquatic pets and has an uncanny ability to detect health issues before they become serious problems.",
    rating: 4,
    reviewCount: 156,
    status: "busy",
    latestReview: {
      name: "Diana",
      text: "Fin told me my fish was suffering from a water quality issue I hadn't detected. After changing the parameters, they're thriving!",
      rating: 5,
    },
    callRate: 1.95,
    chatRate: 1.65,
  },
  {
    id: "pet1",
    name: "Whisper Wilson",
    image: "/images/women_Advisor_1.jpg",
    skills: ["Animal Communication", "Pet Behavior", "Lost Pet Location"],
    description:
      "Whisper can communicate with your pets to understand their needs, behaviors, and help resolve issues they can't express to you directly.",
    rating: 5,
    reviewCount: 478,
    status: "online",
    latestReview: {
      name: "Emma",
      text: "Whisper told me exactly why my cat was avoiding the litter box - it was a health issue the vet later confirmed!",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "pet2",
    name: "Bark Thompson",
    image: "/images/advisorss_2.jpg",
    skills: ["Pet Medium", "Animal Afterlife", "Grief Counseling"],
    description:
      "Bark specializes in connecting with pets who have crossed over, bringing closure and healing messages from your beloved companions.",
    rating: 5,
    reviewCount: 532,
    status: "busy",
    latestReview: {
      name: "Robert",
      text: "The details Bark knew about my deceased dog were impossible to guess. The message he delivered brought me to tears and gave me peace.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "pet3",
    name: "Feather Martinez",
    image: "/images/advisorss_2.jpg",
    skills: ["Bird Whisperer", "Wildlife Communication", "Exotic Pets"],
    description:
      "Feather has a special connection with birds and exotic animals, helping owners understand the unique needs of their unusual companions.",
    rating: 4,
    reviewCount: 187,
    status: "offline",
    latestReview: {
      name: "Tyler",
      text: "My parrot's behavior completely changed after implementing Feather's suggestions. She truly understands avian psychology.",
      rating: 4,
    },
    callRate: 2.15,
    chatRate: 1.85,
  },
  {
    id: "pet4",
    name: "Paws Peterson",
    image: "/images/advisorss_2.jpg",
    skills: ["Pet Trauma Healing", "Behavioral Issues", "Animal Empathy"],
    description:
      "Paws works with rescue animals and pets with trauma, helping them heal emotional wounds and adapt to new environments.",
    rating: 5,
    reviewCount: 321,
    status: "online",
    latestReview: {
      name: "Melissa",
      text: "My rescue dog was terrified of men until Paws helped me understand his past trauma. His transformation has been remarkable.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "pet5",
    name: "Fin Aquarius",
    image: "/images/advisorss_2.jpg",
    skills: ["Aquatic Animals", "Pet Health Intuitive", "Energy Healing for Animals"],
    description:
      "Fin specializes in aquatic pets and has an uncanny ability to detect health issues before they become serious problems.",
    rating: 4,
    reviewCount: 156,
    status: "busy",
    latestReview: {
      name: "Diana",
      text: "Fin told me my fish was suffering from a water quality issue I hadn't detected. After changing the parameters, they're thriving!",
      rating: 5,
    },
    callRate: 1.95,
    chatRate: 1.65,
  },
]

// Money Psychics Advisors
export const moneyPsychicsAdvisors = [
  {
    id: "money1",
    name: "Fortune Goldman",
    image: "/images/advisorss_3.jpg",
    skills: ["Financial Intuition", "Prosperity Paths", "Abundance Blocks"],
    description:
      "Fortune can identify the energetic blocks preventing wealth flow in your life and provide spiritual guidance for financial success.",
    rating: 5,
    reviewCount: 467,
    status: "online",
    latestReview: {
      name: "Victor",
      text: "After clearing the abundance blocks Fortune identified, I received an unexpected promotion with a significant raise.",
      rating: 5,
    },
    callRate: 2.75,
    chatRate: 2.45,
  },
  {
    id: "money2",
    name: "Penny Wisdom",
    image: "/images/advisorss_3.jpg",
    skills: ["Money Manifestation", "Career Guidance", "Investment Intuition"],
    description:
      "Penny combines practical financial advice with psychic insights to help you make decisions that align with your highest financial good.",
    rating: 4,
    reviewCount: 389,
    status: "busy",
    latestReview: {
      name: "Natalie",
      text: "Penny's investment intuition was uncanny. The opportunity she suggested has already yielded returns beyond my expectations.",
      rating: 4,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
  {
    id: "money3",
    name: "Cash Clairvoyant",
    image: "/images/advisorss_3.jpg",
    skills: ["Business Success", "Wealth Timing", "Financial Healing"],
    description:
      "Cash can see the optimal timing for financial moves and business decisions, helping you maximize returns and minimize losses.",
    rating: 5,
    reviewCount: 412,
    status: "offline",
    latestReview: {
      name: "Gregory",
      text: "The timing Cash suggested for launching my business was perfect. We exceeded first-quarter projections by 40%.",
      rating: 5,
    },
    callRate: 2.95,
    chatRate: 2.65,
  },
  {
    id: "money4",
    name: "Wealth Walker",
     image: "/images/advisorss_3.jpg",
    skills: ["Debt Clearing Energy", "Prosperity Rituals", "Abundance Mindset"],
    description:
      "Wealth specializes in clearing the energetic patterns of debt and scarcity, replacing them with powerful abundance frequencies.",
    rating: 5,
    reviewCount: 356,
    status: "online",
    latestReview: {
      name: "Patricia",
      text: "After our prosperity ritual, I finally broke free from a cycle of debt that had plagued me for years. Life-changing!",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "money1",
    name: "Fortune Goldman",
    image: "/images/advisorss_3.jpg",
    skills: ["Financial Intuition", "Prosperity Paths", "Abundance Blocks"],
    description:
      "Fortune can identify the energetic blocks preventing wealth flow in your life and provide spiritual guidance for financial success.",
    rating: 5,
    reviewCount: 467,
    status: "online",
    latestReview: {
      name: "Victor",
      text: "After clearing the abundance blocks Fortune identified, I received an unexpected promotion with a significant raise.",
      rating: 5,
    },
    callRate: 2.75,
    chatRate: 2.45,
  },
  {
    id: "money2",
    name: "Penny Wisdom",
    image: "/images/advisorss_3.jpg",
    skills: ["Money Manifestation", "Career Guidance", "Investment Intuition"],
    description:
      "Penny combines practical financial advice with psychic insights to help you make decisions that align with your highest financial good.",
    rating: 4,
    reviewCount: 389,
    status: "busy",
    latestReview: {
      name: "Natalie",
      text: "Penny's investment intuition was uncanny. The opportunity she suggested has already yielded returns beyond my expectations.",
      rating: 4,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
  {
    id: "money3",
    name: "Cash Clairvoyant",
    image: "/images/advisorss_3.jpg",
    skills: ["Business Success", "Wealth Timing", "Financial Healing"],
    description:
      "Cash can see the optimal timing for financial moves and business decisions, helping you maximize returns and minimize losses.",
    rating: 5,
    reviewCount: 412,
    status: "offline",
    latestReview: {
      name: "Gregory",
      text: "The timing Cash suggested for launching my business was perfect. We exceeded first-quarter projections by 40%.",
      rating: 5,
    },
    callRate: 2.95,
    chatRate: 2.65,
  },
  {
    id: "money4",
    name: "Wealth Walker",
     image: "/images/advisorss_3.jpg",
    skills: ["Debt Clearing Energy", "Prosperity Rituals", "Abundance Mindset"],
    description:
      "Wealth specializes in clearing the energetic patterns of debt and scarcity, replacing them with powerful abundance frequencies.",
    rating: 5,
    reviewCount: 356,
    status: "online",
    latestReview: {
      name: "Patricia",
      text: "After our prosperity ritual, I finally broke free from a cycle of debt that had plagued me for years. Life-changing!",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
]

// Missing Person Psychics Advisors
export const missingPersonPsychicsAdvisors = [
  {
    id: "missing1",
    name: "Finder Ferguson",
     image: "/images/advisorss_4.jpg",
    skills: ["Remote Viewing", "Object Reading", "Location Sensing"],
    description:
      "Finder has assisted in numerous missing persons cases, using his abilities to provide leads and insights when conventional methods fail.",
    rating: 5,
    reviewCount: 312,
    status: "online",
    latestReview: {
      name: "Maria",
      text: "Finder helped locate my missing brother when the police had no leads. His description of the area led directly to finding him.",
      rating: 5,
    },
    callRate: 3.15,
    chatRate: 2.85,
  },
  {
    id: "missing2",
    name: "Seeker Santiago",
     image: "/images/advisorss_4.jpg",
    skills: ["Psychometry", "Missing Persons", "Evidence Intuition"],
    description:
      "Seeker can hold personal items of missing individuals and receive detailed impressions about their location and condition.",
    rating: 5,
    reviewCount: 278,
    status: "busy",
    latestReview: {
      name: "James",
      text: "Seeker described details about my missing daughter's surroundings that led to her recovery. I'm eternally grateful.",
      rating: 5,
    },
    callRate: 3.25,
    chatRate: 2.95,
  },
  {
    id: "missing3",
    name: "Tracker Thompson",
     image: "/images/advisorss_4.jpg",
    skills: ["Psychic Tracking", "Timeline Viewing", "Emotional Connection"],
    description:
      "Tracker specializes in following the energetic trail of missing people, providing insights into their movements and current situation.",
    rating: 4,
    reviewCount: 189,
    status: "offline",
    latestReview: {
      name: "Elizabeth",
      text: "Tracker provided information that helped us locate our missing teenager. His timeline was remarkably accurate.",
      rating: 4,
    },
    callRate: 2.95,
    chatRate: 2.65,
  },
  {
    id: "missing4",
    name: "Locator Lee",
     image: "/images/advisorss_4.jpg",
    skills: ["Map Dowsing", "Photo Reading", "Distance Sensing"],
    description:
      "Locator uses map dowsing and photo reading techniques to narrow down search areas for missing persons with remarkable accuracy.",
    rating: 5,
    reviewCount: 245,
    status: "online",
    latestReview: {
      name: "Richard",
      text: "Locator pinpointed an area on the map where my missing dog was later found. I was amazed by her precision.",
      rating: 5,
    },
    callRate: 2.85,
    chatRate: 2.55,
  },
  {
    id: "missing5",
    name: "Vision Vasquez",
     image: "/images/advisorss_4.jpg",
    skills: ["Clairvoyant Search", "Spirit Communication", "Police Collaboration"],
    description:
      "Vision has worked with law enforcement agencies, providing psychic insights that have contributed to resolving missing persons cases.",
    rating: 5,
    reviewCount: 367,
    status: "busy",
    latestReview: {
      name: "Officer Miller",
      text: "Vision provided details about a missing person case that were later verified. Her insights helped direct our search efforts.",
      rating: 5,
    },
    callRate: 3.35,
    chatRate: 3.05,
  },
]

// Break-up Psychics Advisors
export const breakupPsychicsAdvisors = [
  {
    id: "breakup1",
    name: "Healer Hart",
     image: "/images/advisorss_5.jpg",
    skills: ["Heartbreak Healing", "Emotional Recovery", "Future Love"],
    description:
      "Healer specializes in guiding you through the painful aftermath of a breakup, helping you process emotions and see the path forward.",
    rating: 5,
    reviewCount: 478,
    status: "online",
    latestReview: {
      name: "Jennifer",
      text: "Healer's guidance helped me move through my grief after my divorce in a healthy way. I'm now ready to open my heart again.",
      rating: 5,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "breakup2",
    name: "Mend Michaels",
     image: "/images/advisorss_5.jpg",
    skills: ["Relationship Closure", "Soul Contracts", "Karmic Lessons"],
    description:
      "Mend helps you understand the deeper purpose of your relationship and breakup, revealing the soul lessons and growth opportunities.",
    rating: 5,
    reviewCount: 412,
    status: "busy",
    latestReview: {
      name: "Carlos",
      text: "Understanding the soul contract behind my painful breakup transformed my perspective completely. Thank you, Mend.",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "breakup3",
    name: "Release Rivera",
     image: "/images/advisorss_5.jpg",
    skills: ["Cord Cutting", "Energy Clearing", "Attachment Release"],
    description:
      "Release performs energetic cord-cutting ceremonies to help you break unhealthy attachments to ex-partners and reclaim your energy.",
    rating: 5,
    reviewCount: 356,
    status: "offline",
    latestReview: {
      name: "Sophia",
      text: "After Release's cord-cutting session, I felt lighter than I had in years. The obsessive thoughts about my ex finally stopped.",
      rating: 5,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
  {
    id: "breakup4",
    name: "Forward Francis",
     image: "/images/advisorss_5.jpg",
    skills: ["Future Love Reading", "Self-Discovery", "Relationship Patterns"],
    description:
      "Forward helps you identify and break negative relationship patterns while providing insights into your future romantic possibilities.",
    rating: 4,
    reviewCount: 289,
    status: "online",
    latestReview: {
      name: "Aiden",
      text: "Forward helped me see how I was repeating the same patterns in my relationships. Now I'm dating someone completely different - in a good way!",
      rating: 4,
    },
    callRate: 2.25,
    chatRate: 1.95,
  },
]

// Cheating Affairs Advisors
export const cheatingAffairsAdvisors = [
  {
    id: "cheating1",
    name: "Truth Teller",
     image: "/images/advisorss_6.jpg",
    skills: ["Infidelity Insights", "Relationship Reading", "Truth Seeking"],
    description:
      "Truth Teller provides clear, compassionate insights into suspected infidelity, helping you uncover facts and make informed decisions.",
    rating: 5,
    reviewCount: 523,
    status: "online",
    latestReview: {
      name: "Vanessa",
      text: "Truth Teller confirmed my suspicions with specific details I later verified. His compassionate approach helped me through a difficult time.",
      rating: 5,
    },
    callRate: 2.75,
    chatRate: 2.45,
  },
  {
    id: "cheating2",
    name: "Clarity Clark",
     image: "/images/advisorss_6.jpg",
    skills: ["Relationship Transparency", "Partner Intentions", "Future Outcomes"],
    description:
      "Clarity helps you see the complete picture in your relationship, revealing hidden dynamics and potential paths forward.",
    rating: 5,
    reviewCount: 467,
    status: "busy",
    latestReview: {
      name: "Marcus",
      text: "Clarity helped me understand why my partner was unfaithful and whether reconciliation was possible. Her insights were invaluable.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "cheating3",
    name: "Reveal Rodriguez",
     image: "/images/advisorss_6.jpg",
    skills: ["Deception Detection", "Emotional Healing", "Relationship Guidance"],
    description:
      "Reveal specializes in uncovering deception while providing emotional support and guidance for your next steps.",
    rating: 4,
    reviewCount: 312,
    status: "offline",
    latestReview: {
      name: "Kimberly",
      text: "Reveal not only confirmed my partner's affair but helped me process my emotions and decide whether to stay or leave.",
      rating: 4,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "cheating4",
    name: "Insight Ivanov",
    image: "/images/advisorss_6.jpg",
    skills: ["Affair Detection", "Relationship Repair", "Trust Building"],
    description:
      "Insight provides clarity about infidelity situations and specializes in guidance for couples who wish to rebuild after betrayal.",
    rating: 5,
    reviewCount: 389,
    status: "online",
    latestReview: {
      name: "Rachel",
      text: "Thanks to Insight's guidance, my husband and I were able to rebuild trust after his affair. We're stronger than ever now.",
      rating: 5,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
  {
    id: "cheating5",
    name: "Fidelity Fisher",
   image: "/images/advisorss_6.jpg",
    skills: ["Loyalty Reading", "Relationship Energy", "Future Fidelity"],
    description:
      "Fidelity assesses the loyalty in your relationship and provides insights into whether a partner is likely to remain faithful in the future.",
    rating: 4,
    reviewCount: 278,
    status: "busy",
    latestReview: {
      name: "Brandon",
      text: "Fidelity's assessment of my new relationship gave me peace of mind after my previous experience with infidelity.",
      rating: 4,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
]

// Family Affairs Advisors
export const familyAffairsAdvisors = [
  {
    id: "family1",
    name: "Harmony Holmes",
    image: "/images/advisorss_7.jpg",
    skills: ["Family Dynamics", "Conflict Resolution", "Ancestral Patterns"],
    description:
      "Harmony helps identify and heal dysfunctional family patterns, bringing greater understanding and peace to family relationships.",
    rating: 5,
    reviewCount: 456,
    status: "online",
    latestReview: {
      name: "Gabriella",
      text: "Harmony helped our family understand the generational patterns causing our conflicts. Our family gatherings are peaceful now.",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "family2",
    name: "Legacy Lee",
    image: "/images/advisorss_7.jpg",
    skills: ["Ancestral Healing", "Family Karma", "Generational Blessings"],
    description:
      "Legacy specializes in identifying and healing ancestral wounds that affect current family dynamics and individual life paths.",
    rating: 5,
    reviewCount: 389,
    status: "busy",
    latestReview: {
      name: "Miguel",
      text: "The ancestral healing session with Legacy explained so much about our family's recurring struggles. We've begun to break the cycle.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "family3",
    name: "Kinship Kelly",
   image: "/images/advisorss_7.jpg",
    skills: ["Sibling Relationships", "Family Reconciliation", "Estrangement Healing"],
    description:
      "Kinship specializes in healing broken family bonds, particularly between siblings or in cases of estrangement.",
    rating: 4,
    reviewCount: 312,
    status: "offline",
    latestReview: {
      name: "Olivia",
      text: "After years of not speaking to my sister, Kinship helped us understand each other and rebuild our relationship.",
      rating: 4,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "family4",
    name: "Roots Rivera",
    image: "/images/advisorss_7.jpg",
    skills: ["Family Tree Reading", "Inherited Gifts", "Ancestral Messages"],
    description:
      "Roots connects with your family lineage to reveal inherited spiritual gifts and messages from ancestors that can guide your path.",
    rating: 5,
    reviewCount: 345,
    status: "online",
    latestReview: {
      name: "Liam",
      text: "Roots helped me discover artistic talents that run in my family line. I've since taken up painting and feel deeply connected to my ancestors.",
      rating: 5,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
]

// Marital Life Advisors
export const maritalLifeAdvisors = [
  {
    id: "marital1",
    name: "Union Unger",
    image: "/images/advisorss_8.jpg",
    skills: ["Marriage Harmony", "Couple's Energy", "Relationship Renewal"],
    description:
      "Union specializes in restoring harmony to marriages by identifying energetic imbalances and providing spiritual tools for reconnection.",
    rating: 5,
    reviewCount: 489,
    status: "online",
    latestReview: {
      name: "Rebecca",
      text: "Union's insights saved our marriage. The spiritual practices he suggested have transformed how my husband and I connect.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "marital2",
    name: "Vow Validator",
    image: "/images/advisorss_8.jpg",
    skills: ["Commitment Reading", "Marriage Potential", "Partner Compatibility"],
    description:
      "Vow assesses the strength and potential of marital bonds, helping couples understand their compatibility on a soul level.",
    rating: 4,
    reviewCount: 356,
    status: "busy",
    latestReview: {
      name: "Jonathan",
      text: "Vow's compatibility reading for my fiancée and me highlighted areas we needed to work on before marriage. Her insights were invaluable.",
      rating: 4,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "marital3",
    name: "Bond Builder",
    image: "/images/advisorss_8.jpg",
    skills: ["Marital Healing", "Intimacy Restoration", "Communication Enhancement"],
    description:
      "Bond specializes in rebuilding the emotional and spiritual connection between spouses, particularly after periods of distance or conflict.",
    rating: 5,
    reviewCount: 412,
    status: "offline",
    latestReview: {
      name: "Sophia",
      text: "After years of feeling like roommates, Bond helped my husband and I rediscover our deep connection and fall in love again.",
      rating: 5,
    },
    callRate: 2.75,
    chatRate: 2.45,
  },
  {
    id: "marital4",
    name: "Eternal Evans",
    image: "/images/advisorss_8.jpg",
    skills: ["Long-term Love", "Marriage Longevity", "Relationship Evolution"],
    description:
      "Eternal helps couples navigate the different phases of marriage, ensuring your relationship continues to evolve and deepen over time.",
    rating: 5,
    reviewCount: 378,
    status: "online",
    latestReview: {
      name: "David",
      text: "As empty-nesters, my wife and I were struggling to redefine our relationship. Eternal's guidance has led to a beautiful new chapter.",
      rating: 5,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
  {
    id: "marital5",
    name: "Sacred Smith",
    image: "/images/advisorss_8.jpg",
    skills: ["Spiritual Marriage", "Soul Contracts", "Divine Partnership"],
    description:
      "Sacred views marriage through a spiritual lens, helping couples understand the sacred purpose of their union and its higher calling.",
    rating: 5,
    reviewCount: 289,
    status: "busy",
    latestReview: {
      name: "Priya",
      text: "Understanding the spiritual purpose of our marriage has transformed how my husband and I approach challenges. We now see them as opportunities for growth.",
      rating: 5,
    },
    callRate: 2.85,
    chatRate: 2.55,
  },
]

// Parent & Children Advisors
export const parentChildrenAdvisors = [
  {
    id: "parent1",
    name: "Nurture Nelson",
    image: "/images/advisorss_9.jpg",
    skills: ["Child Reading", "Parenting Guidance", "Family Harmony"],
    description:
      "Nurture helps parents understand their children's unique needs, gifts, and challenges from a spiritual perspective.",
    rating: 5,
    reviewCount: 467,
    status: "online",
    latestReview: {
      name: "Amanda",
      text: "Nurture helped me understand my son's sensitivity in a whole new light. Our relationship has improved dramatically.",
      rating: 5,
    },
    callRate: 2.45,
    chatRate: 2.15,
  },
  {
    id: "parent2",
    name: "Guardian Garcia",
    image: "/images/advisorss_9.jpg",
    skills: ["Child Spirit Guides", "Intuitive Parenting", "Family Soul Plan"],
    description:
      "Guardian connects with children's spirit guides to provide insights into their life purpose and how parents can best support their journey.",
    rating: 5,
    reviewCount: 389,
    status: "busy",
    latestReview: {
      name: "Thomas",
      text: "The information about my daughter's spiritual gifts was eye-opening. Guardian helped me understand how to nurture her unique abilities.",
      rating: 5,
    },
    callRate: 2.65,
    chatRate: 2.35,
  },
  {
    id: "parent3",
    name: "Legacy Lewis",
    image: "/images/advisorss_9.jpg",
    skills: ["Generational Healing", "Parent-Child Karma", "Family Patterns"],
    description:
      "Legacy helps parents break negative generational patterns and create healthier relationships with their children than they experienced.",
    rating: 4,
    reviewCount: 312,
    status: "offline",
    latestReview: {
      name: "Michael",
      text: "Legacy helped me see how I was repeating my father's parenting mistakes. With her guidance, I'm creating a new legacy for my children.",
      rating: 4,
    },
    callRate: 2.35,
    chatRate: 2.05,
  },
  {
    id: "parent4",
    name: "Bond Builder Jr.",
    image: "/images/advisorss_9.jpg",
    skills: ["Teen Communication", "Parent-Child Connection", "Family Mediation"],
    description:
      "Bond Jr. specializes in healing and strengthening the relationship between parents and teenagers during challenging transitional years.",
    rating: 5,
    reviewCount: 356,
    status: "online",
    latestReview: {
      name: "Jennifer",
      text: "Our household was a war zone with our teenage daughter until Bond Jr. helped us understand what was really happening. Peace has been restored!",
      rating: 5,
    },
    callRate: 2.55,
    chatRate: 2.25,
  },
]
